### PR TITLE
Duo iframe gets cached which causes it to not init until document.ready. We want to always load a new iframe.

### PR DESCRIPTION
**Pull request by mehtadev17**

### CODE REVIEW

**Comment by mehtadev17** [comment]
@JakePayton

**Comment by Cole-Beckwith-SP** [comment]
Just pulled it in. This resolves our issue.

**Comment by Cole-Beckwith-SP** [comment]
Doesn't seem to work in Firefox or IE11 though.

**Comment by justcolin** [comment]
Thank you for submitting this PR! We ended up taking a slightly different solution to this problem (#13), but your PR definitely helped.

If you get a chance to update to version 2.7 of the Duo Web SDK and still experience problems with multiple calls to `init()` let us know by opening another issue or PR.

**Pull request closed without merging**
